[package]
name = "rust-project-template"
version = "0.1.0"
edition = "2024"

[dependencies]
log={ version = "0.4.27", features = ["kv", "kv_serde"] }
env_logger={ version = "0.11.8", features = ["unstable-kv"] }
clap = { version = "4.5.35", features = ["derive"] }
