[package]
name = "rust-project-template"
version = "0.1.0"
edition = "2024"

[dependencies]
log={ version = "0.4.26", features = ["kv", "kv_serde"] }
env_logger={ version = "0.11.6", features = ["unstable-kv"] }
